// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjsVo8mmqgDpS0E1GtrQo_YpuhufP1_w4',
    appId: '1:390085045430:web:9680ec30fc3e304b3c8a17',
    messagingSenderId: '390085045430',
    projectId: 'shop-app-7165a',
    authDomain: 'shop-app-7165a.firebaseapp.com',
    storageBucket: 'shop-app-7165a.appspot.com',
    measurementId: 'G-88PE67RTNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNo3LbTiDWOFp53DAxqZEiJTLw8njE42g',
    appId: '1:390085045430:android:a606dd246cbaac243c8a17',
    messagingSenderId: '390085045430',
    projectId: 'shop-app-7165a',
    storageBucket: 'shop-app-7165a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9kaz1CF0ZGkO0XJMa6NYHH0whHakbtWI',
    appId: '1:390085045430:ios:83f3eba7c4a0b73e3c8a17',
    messagingSenderId: '390085045430',
    projectId: 'shop-app-7165a',
    storageBucket: 'shop-app-7165a.appspot.com',
    androidClientId: '390085045430-3291n5ipi6t9ahh1n86qn6febhm79s7l.apps.googleusercontent.com',
    iosClientId: '390085045430-3ubqupl95vqbp90h7qatmslou4t5vtn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9kaz1CF0ZGkO0XJMa6NYHH0whHakbtWI',
    appId: '1:390085045430:ios:2054d670bc099aa93c8a17',
    messagingSenderId: '390085045430',
    projectId: 'shop-app-7165a',
    storageBucket: 'shop-app-7165a.appspot.com',
    androidClientId: '390085045430-3291n5ipi6t9ahh1n86qn6febhm79s7l.apps.googleusercontent.com',
    iosClientId: '390085045430-v088umuijljk7d5ptvpc8js99tai79q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp.RunnerTests',
  );
}
